---
- name: Install packages
  apt: name={{ item }} state=present
  with_items:
    - php5-pgsql
    - php5-curl
    - curl
    - php5-mcrypt
    - php5-cli
    - git
    - php5-common
    - php5-fpm
    - python-psycopg2
    - nginx
    - postgresql

- name: Set php configs
  ini_file: dest="/etc/php5/fpm/php.ini" section="PHP" option="cgi.fix_pathinfo" value="0"
  notify: restart php-fpm

- name: Set php-fpm configs
  ini_file: dest=/etc/php5/fpm/pool.d/www.conf section=www option={{ item.0 }} value={{ item.1 }}
  with_together:
    - [ 'listen', 'listen.owner', 'listen.group', 'listen.mode' ]
    - [ '/var/run/php5-fpm.sock', 'www-data', 'www-data', '0660' ]
  notify: restart php-fpm

- name: Set Nginx configs
  lineinfile: dest=/etc/nginx/fastcgi_params regexp='^fastcgi_param\W+PATH_TRANSLATED ' line='fastcgi_param PATH_TRANSLATED \$document_root\$fastcgi_script_name;'
  notify: restart nginx

- name: Start services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - postgresql
    - php5-fpm
    - nginx
