---
- name: Download TTRSS
  git: repo=https://github.com/gothfox/Tiny-Tiny-RSS.git dest=/var/www/ttrss
  notify: clear ttrss cache

- name: Set TTRSS permissions
  file: path=/var/www/ttrss/{{ item }} owner=www-data group=www-data
  with_items:
    - cache
    - cache/export
    - cache/images
    - cache/js
    - cache/simplepie
    - cache/upload
    - feed-icons
    - lock

- name: Install ttrss config file
  template: dest=/var/www/ttrss/config.php src=ttrss-config.php owner=www-data group=www-data mode=0600

- name: Setup nginx location for ttrss
  template: dest=/etc/nginx/apps-available/ttrss src=ttrss_nginx.conf
  notify: restart nginx

- name: Enable nginx location for ttrss
  file: path=/etc/nginx/apps-enabled/ttrss state=link src=/etc/nginx/apps-available/ttrss
  notify: restart nginx

- name: Install cron task for updates
  cron:
    user: www-data
    name: ttrss_update
    hour: '*/3'
    job: /usr/bin/php /var/www/ttrss/update.php --feeds --quiet

