---
- name: Download TTRSS
  git: repo=https://github.com/gothfox/Tiny-Tiny-RSS.git dest=/var/www/ttrss
  notify: clear ttrss cache

- name: Set TTRSS permissions
  file: path=/var/www/ttrss/{{ item }} owner=www-data group=www-data
  with_items:
    - cache
    - cache/export
    - cache/images
    - cache/js
    - cache/simplepie
    - cache/upload
    - feed-icons
    - lock

- name: Install ttrss config file
  template: dest=/var/www/ttrss/config.php src=ttrss-config.php owner=www-data group=www-data mode=0600

- name: Remove nginix default site
  file: path=/etc/nginx/{{ item }}/default state=absent
  with_items:
    - sites-enabled
    - sites-available
  notify: restart nginx
  when: not keep_default_nginx_site

- name: Install ssl certificate
  copy: src=ttrss.crt dest='/etc/ssl/certs/{{ ttrss_hostname }}.crt' owner=root group=root mode=0644
  when: ttrss_use_https and not ttrss_cert_path
  notify: restart nginx

- name: Install ssl certificate key
  copy: src=ttrss.key dest='/etc/ssl/private/{{ ttrss_hostname }}.key' owner=root group=ssl-cert mode=0640
  when: ttrss_use_https and not ttrss_cert_key_path
  notify: restart nginx

- name: Setup nginx site config for ttrss
  template: dest=/etc/nginx/sites-available/ttrss src=nginx.conf
  notify: restart nginx

- name: Enable ttrss site in nginx
  file: path=/etc/nginx/sites-enabled/ttrss state=link src=/etc/nginx/sites-available/ttrss
  notify: restart nginx

- name: Install cron task for updates
  cron:
    user: www-data
    name: ttrss_update
    hour: '*/3'
    job: /usr/bin/php /var/www/ttrss/update.php --feeds --quiet

