---
- name: Install PostgreSQL package
  apt: name=postgresql state=present update_cache=yes cache_valid_time=86400

- name: Start Postgres Service
  service: name=postgresql state=started enabled=yes
